AI/urls.py
from django.urls import path
from . import views

app_name = 'AI'

urlpatterns = [
    path('gpt', views.gpt, name='gpt'),
    path('slides', views.genppt, name='slides'),
    path('slides/refresh/<int:id>', views.refresh_state, name='slides_refresh'),
]

ailearn/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('native-admin/', admin.site.urls),
    path('', include('index.urls')),
    path('user/', include('user.urls')),
    path('problem/', include('problem.urls')),
    path('zone/', include('zone.urls')),
    path('chat/', include('chat.urls')),
    path('ai/', include('AI.urls')),
    path('tag/', include('tag.urls')),
    path('paper/', include('paper.urls')),
    path('admin/', include('adminc.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

problem/urls.py
from django.urls import path
from . import views

app_name = 'problem'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:id>/', views.view, name='view'),
    path('solution/<int:id>/', views.view_solution, name='view_solution'),
    path('new/', views.new, name='new'),
    path('generate/', views.generate, name='generate'),
]

problem/models.py
from django.db import models
import datetime
from django.utils import timezone

from user.models import *

def now():
    return timezone.now()

class Problem(models.Model):
    facility = models.ForeignKey(Facility, on_delete = models.CASCADE, null = True)
    creator = models.ForeignKey(User, on_delete = models.CASCADE)
    title = models.CharField(max_length = 255)
    type = models.CharField(max_length = 16)
    statement = models.TextField(max_length = 4096)
    answer = models.TextField(max_length = 4096)
    date = models.DateTimeField(default = now)

class Solution(models.Model):
    creator = models.ForeignKey(User, on_delete = models.CASCADE)
    problem = models.ForeignKey(Problem, on_delete = models.CASCADE)
    content = models.TextField(max_length = 4096)
    score = models.FloatField(null = True)
    date = models.DateTimeField(default = now)

class SlnComment(models.Model):
    solution = models.ForeignKey(Solution, null = True, on_delete = models.CASCADE)
    author = models.ForeignKey(User, on_delete = models.CASCADE)
    content = models.TextField()
    date = models.DateTimeField(default = now)

tag/models.py
from django.db import models
from problem.models import  Problem
from zone.models import Post
from user.models import User

class Tag(models.Model):
    text = models.TextField(max_length=10)
    problems = models.ManyToManyField(Problem)
    post = models.ManyToManyField(Post)
    user = models.ManyToManyField(User)

class UserTagWeight(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    tag = models.ForeignKey(Tag, on_delete=models.CASCADE)
    weight = models.IntegerField('weight', default=0)

problem/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.http.request import HttpRequest
from django.http.response import HttpResponseBadRequest
from django.http import JsonResponse, HttpResponse
from django.db.models import Count, Max, Q
import asyncio
from dotenv import load_dotenv
from functional import seq
import json
import re
from .models import *
from tag.models import *
import openai
from functools import reduce
from problem.templatetags.markdown import unmarkup
from rest_framework.decorators import api_view, permission_classes
from rest_framework.permissions import IsAuthenticated
from rest_framework.exceptions import AuthenticationFailed
from user.views import get_user_from_token
from rest_framework.response import Response

load_dotenv()

OPENAI_API_KEY = os.getenv('OPENAI_KEY')

@permission_classes([IsAuthenticated])
def index(request: HttpRequest):
    token = request.headers.get('Authorization')
    user = get_user_from_token(token)
    if request.method == 'GET':
        problems = Problem.objects.filter(facility = user.facility) \
                          .annotate(latest_solution = Max('solution__id'))
        tags = Tag.objects.filter(problems__facility=user.facility).distinct()
        return JsonResponse({
            'data':{
                'problems': problems,
                'tags': tags,
                'user': user
            },
            'status': 200
        })
    if request.method == 'POST':
        print(request.POST['type'])
        if request.POST['type'] == 'search':
            tags = json.loads(request.POST['tags'])
            result = reduce(lambda qs, tag: qs.filter(tag__id = tag), tags, Problem.objects.filter(facility=user.facility))
            print(result)
            print({
                'result': seq(result.values()).map(lambda x: {
                    **x,
                    'statement': unmarkup(x['statement'])
                }).to_list()
            })
            return JsonResponse({
                'result': seq(result.values()).map(lambda x: {
                    **x,
                    'statement': unmarkup(x['statement'])
                }).to_list()
            }, safe=False)

    
@permission_classes([IsAuthenticated])
def generate(request: HttpRequest):
    token = request.headers.get('Authorization')
    user = get_user_from_token(token)
    if request.method == 'POST':
        asyncio.run(asyncio.sleep(1))

        openai.api_key = OPENAI_API_KEY
        openai.base_url = 'https://api.ai-yyds.com/v1/'

        statement = ''
        while '?' not in statement and '？' not in statement:
            messages1 = [
                {
                    'role': 'user',
                    'content': f"请你根据：{request.POST['keyword']}这段描述生成一道历史题目。题干不要超过100字，题干中绝对不能包含答案，题干必须是一个疑问句，你的输出绝对不能包含题干之外的任何内容"
                }
            ]
            response1 = openai.chat.completions.create(
                    messages=messages1,
                    model='gpt-3.5-turbo'
                )
            statement = response1.choices[0].message.content

        
        messages2 = [
            {
                'role': 'user',
                'content': f"{statement},以上是一道历史题目的题干，请你给出这道历史题目的答案，应该尽量简短，你的输出绝对不能包含答案之外的任何内容"
            },
        ]
        response2 = openai.chat.completions.create(
                messages=messages2,
                model='gpt-3.5-turbo'
            )
        answer = response2.choices[0].message.content
        
        print(statement, answer)
        return JsonResponse({
            'statement': statement,
            'answer': answer,
        })
@permission_classes([IsAuthenticated])
def view(request: HttpRequest, id: int):
    token = request.headers.get('Authorization')
    user = get_user_from_token(token)
    problem = Problem.objects.get(id = id)
    solutions = Solution.objects.filter(problem=problem)
    if request.method == 'GET':
        return JsonResponse({
            'data':{
                'problem': problem,
                'solutions': solutions,
            },
            'status': 200
        })
    elif request.method == 'POST':
        sln = Solution.objects.create(
            creator = user,
            problem = problem,
            content = request.POST['content']
        )
        sln.save()
        return Response({
            'data': {
                'solution': sln.id
            }
        }, status=200)
@permission_classes([IsAuthenticated])
def view_solution(request: HttpRequest, id: int):
    token = request.headers.get('Authorization')
    user = get_user_from_token(token)
    try:
        sln = Solution.objects.get(id = id)
        comment = SlnComment.objects.filter(solution=sln)
    except Solution.DoesNotExist:
        return Response(status=404)

    if request.method == 'GET':
        return Response({
            'data': {
                'solution': sln,
                'comments': comment
            }
        }, status=200)
    if request.method == 'POST':
        comment = SlnComment.objects.create(author=user, content=request.POST['comment'], solution=sln)
        return Response(status=200, data={'data':{
          'id' : id
        } }
                        )
@permission_classes([IsAuthenticated])
def new(request: HttpRequest):
    token = request.headers.get('Authorization')
    user = get_user_from_token(token)
    if user.role != 'teacher':
        return Response(status=403)
    elif request.method == 'POST':
        problem = Problem.objects.create(
            facility = user.facility,
            creator = user,
            title = request.POST['title'],
            statement = request.POST['statement'],
            answer = request.POST['answer'],
        )
        if request.POST['tag']:
            tags = seq(request.POST['tag'].split(';')).map(lambda s: s.strip()).filter(lambda s: bool(s))
            for t in tags:
                tag = Tag.objects.filter(text=t).first()

                if tag is None:
                    tag = Tag.objects.create(text = t)

                tag.problems.add(problem)
            
            tag.save()

        problem.save()

        return Response(status=200, data={'data':{
            'problem': problem.id
        }})

problem/templates/problem/base.html
{% extends "base.html" %}

{% load static %}

{% block topmenu %}
<a class="item" href="{% url 'problem:index' %}" data-slave-app="problem">
    <i class="fa-solid fa-list"></i> 题目列表
</a>

{% if request.user.role == 'teacher' %}
<a class="item" href="{% url 'problem:new' %}" data-slave-app="problem">
    <i class="fa-solid fa-plus"></i> 新建题目
</a>
{% endif %}


{% endblock %}

problem/templates/problem/index.html
{% extends "problem/base.html" %}
{% load static %}

{% block content %}

<style>
    .ui.celled.padded.center.aligned.table {
        background-color: rgba(255, 255, 255, 0.8);
    }
    .list {
        max-height: 60%;
        flex: auto;
    }
</style>
<input type="hidden" id="ajax-url" value='{% url "problem:index" %}'>
<input type="hidden" id="csrf-token" value='{{csrf_token}}'>
<div class="ui center aligned grid" style="padding-top: 24px;">
    <div class="row">
        <h1>
            题目
        </h1>
    </div>
    <div class="eleven wide computer eleven wide tablet sixteen wide mobile column">
        <table class="ui celled padded center aligned table list">
            <thead >
                <tr>
                    <th style="background-color: #ffffff00;">题目ID</th>
                    <th style="background-color: #ffffff00;">标题</th>
                    <th style="background-color: #ffffff00;">标签</th>
                   
                </tr>
            </thead>

            <tbody>
                {% for problem in problems %}
                <tr>
                    <td>
                        {{ problem.id }}
                    </td>
                    <td>
                        <a href="{% url 'problem:view' problem.id %}">
                            {{ problem.title }}
                        </a>
                    </td>
                    <td>
                        {% for tag in problem.tag_set.all %}
                        <span class="tag">
                            <i class="fa-solid fa-tag"></i>
                            {{ tag.text }}
                        </span>
                        {% endfor %}
                    </td>
                    <!-- <td>
                        {% if problem.latest_solution %}
                        <a href="{% url 'problem:view_solution' problem.latest_solution %}">
                            查看题解
                        </a>
                        {% else %}
                        <i>无题解</i>
                        {% endif %}
                    </td> -->
                </tr>
                {% endfor %}
            </tbody>

            {% if request.user.role == "teacher" %}
            <tfoot>
                <tr>
                    <th colspan="4" style="background-color: #ffffff00;">
                        <a class="ui right floated green button" href="{% url 'problem:new' %}" style="background-color: rgba(91, 135, 91, 0.626);">
                            <i class="fa-solid fa-plus"></i> 新建题目
                        </a>
                    </th>
                </tr>
            </tfoot>
            {% endif %}

        </table>
    </div>
    <div class="four wide column">
        <div class="ui form segment" style="min-height: 100%; background-color: #ffffffe2;">
            <div class="ui inverted dimmer">
                <div class="ui text loader">正在加载</div>
            </div>
            <div class="field">
                <div class="ui multiple search selection dropdown">
                    <input type="hidden" name="tags">
                    <i class="dropdown icon"></i>
                    <div class="default text">按标签搜索</div>
                    <div class="menu">
                        {% for tag in tags %}
                        <div class="item" data-value="{{ tag.id }}">{{ tag.text }}</div>
                        {% endfor %}
                    </div>
                </div>
            </div>
            <div class="ui left aligned middle aligned container">
                <div class="ui relaxed list" id="search-results">
                </div>
            </div>
        </div>
    </div>
</div>
<script src="{% static 'js/problem/problem.js' %}"></script>
{% endblock %}

problem/templates/problem/new.html
{% extends "problem/base.html" %}

{% load static %}

{% block content %}
<script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
<script id="MathJax-script" async src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"></script>


<style>
    .editor-container {
        text-align: left !important;
    }
</style>
<div class="ui center aligned grid">
    <div class="ui inverted dimmer" id="dimmer">
        <div class="ui text loader">正在请求</div>
    </div>

    <div class="row">
        <div class="ui nine wide computer nine wide tablet fourteen wide mobile column segment" style="background-color: #ffffffc1;">
            <h1>
                新建题目
            </h1>
            <form method="POST">
                {% csrf_token %}
                <div class="ui form">
                    <div class="field">
                        <input type="text" name="title" placeholder="题目标题" id="input-title" required>
                    </div>

                    <div class="field editor-container">
                        <textarea id="editor"></textarea>
                    </div>

                    <input type="hidden" name="statement">

                    <div class="field">
                        <textarea name="answer" placeholder="参考答案" id="input-answer" required></textarea>
                    </div>

                    <div class="field">
                        <input name="tag" placeholder="题目标签 用 ; 分隔" id="input-tag" required>
                    </div>

                    <button class="ui button" type="submit">GO</button>
                </div>
            </form>
        </div>

        <div class="ui four wide computer four wide tablet fourteen wide mobile column segment" style="background-color: #ffffffc1;">
            <h1>
                生成
            </h1>
            <div class="ui form">
                <div class="field">
                    <textarea placeholder="在这里输入描述，例如“生成关于图灵的题目”" id="input-keyword"></textarea>
                </div>

                <button class="ui button" id="button-generate">GO</button>
            </div>
        </div>
    </div>

</div>

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/easymde/dist/easymde.min.css">
<script src="https://cdn.jsdelivr.net/npm/easymde/dist/easymde.min.js"></script>

<script>
    const mde = new EasyMDE({
        element: document.getElementById('editor'),
        minHeight: '300px',
        maxHeight: '300px',
        spellChecker: false,
        placeholder: '题目描述'
    });

    $('form').submit(function () {
        $(this).find('input[name="statement"]').val(mde.value());
        return true;
    });

    $('#button-generate').click(function (e) {
        $('#dimmer').toggleClass('active');

        $.ajax({
            method: 'POST',
            url: "{% url 'problem:generate' %}",
            data: {
                keyword: $('#input-keyword').val(),
                template: 'problem',
                type: 'generateProblem'
            },
            headers: {
                'X-CSRFToken': '{{ csrf_token }}'
            },
            success: data => {
                mde.value(data.statement);
                $('#input-answer').val(data.answer);
            }
        }).always(() => {
            $('#dimmer').toggleClass('active');
        });
    })

</script>

{% endblock %}

problem/templates/problem/view.html
{% extends "problem/base.html" %}
{% load static %}
{% load markdown %}

{% block content %}

<script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
<script id="MathJax-script" async src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"></script>
<div class="ui center aligned grid">
    <div class="ui eleven wide column segment" style="background-color: #ffffffc1;">
        <h1>
            {{ problem.title }}
        </h1>

        <div class="ui divider"></div>

        <div style="margin-top: 24px; margin-bottom: 24px;">
            {{ problem.statement | markdown | safe }}
        </div>
        {% if request.user.role == 'teacher' or request.user.role == 'student'%}
        <div class="ui form">
            <form method="POST">
                {% csrf_token %}
                <div class="field">
                    <textarea style="background-color: rgba(255, 255, 255, 0.5);" placeholder="写下你的答案" name="content"
                        required></textarea>
                </div>

                <button class="ui button" type="submit" style="background-color: rgba(36, 131, 165, 0.5);">
                    <i class="fa-solid fa-check"></i>
                    提交
                </button>
            </form>
        </div>
        {% endif %}
    </div>
    <div class="row">
        <div class="ui eleven wide column segment" style="background-color: #ffffffc1;">
            <div id="answer" style="display: none;">
                {% for sln in solutions %}
                <div class="ui vertical segment">
                    <h4>
                        <a href="{% url 'problem:view_solution' sln.id %}" style="color: black;">
                            {{ sln.creator }}
                        </a>
                    </h4>
                    <div class="description">
                        {{ sln.content | truncatechars:32 }}
                    </div>
                </div>
                {% endfor %}
            </div>
            <div class="ui buttons">
                <button class="ui button" id="hide-button">隐藏他人作答</button>
                <div class="or"></div>
                <button class="ui positive button" id="show-button">参考他人作答</button>
            </div>
        </div>
    </div>
</div>
<script>
    $(function() {
        $('#show-button').click(function() {
            $('#answer').fadeIn();
        })
        $('#hide-button').click(function() {
            $('#answer').fadeOut();
        })
    });
</script>
{% endblock %}

problem/templates/problem/view_solution.html
{% extends "problem/base.html" %}
{% load static %}
{% load markdown %}
{% block content %}

<div class="ui center aligned grid">
    <div class="ui twelve wide mobile column segment" style="background-color: #ffffffc1;">
        <p>
            {{ solution.problem.statement | markdown | safe }}
        </p>
        <div class="ui divider"></div>
        <div class="ui text container">
            <div class="twelve wide mobile column">
                <p>
                    {{ solution.content }}
                </p>
            </div>
        </div>
        <div class="ui divider"></div>
        <p>
            解答来自: {{solution.creator}}
        </p>
    </div>
<div class="row">
    <div class="ten wide computer ten wide tablet sixteen wide mobile column">
        <div class="ui text container" >
            <form method="POST">
                {% csrf_token %}
                <div class="ui form">
                    <div class="field" style="display: flex;">
                        <input name="comment" placeholder="点评一下这篇题解" required>
                        <button class="ui button" type="submit" style="font-weight: bold;">OK</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
<div class="row">
    <div class="ui text container comment-container">
        <div class="ui segment" id="post-back" style="background-color: #ffffffc1;">
        {% for comment in comments %}
        <div class="ui left aligned container comment" style="margin: 12px;"
            data-reply="{{ comment.reply.id | default:'' }}" data-id="{{ comment.id }}">
            
            <span>
                <b>
                    {{ comment.author.username }}
                </b>
                <span class="comment-date"> #{{ comment.id }} {{ comment.date|date:"Y/m/d H:i:s" }}</span>
            </span>
            <p>
                {{ comment.content }}
            </p>

            <div class="reply-container">
            </div>
        </div>
        {% empty %}
        <i>
            看起来还没有人点评这篇题解
        </i>
    </div>
        {% endfor %}
    </div>
</div>
</div>

{% endblock %}