AI/urls.py
from django.urls import path
from . import views

app_name = 'AI'

urlpatterns = [
    path('gpt', views.gpt, name='gpt'),
    path('slides', views.genppt, name='slides'),
    path('slides/refresh/<int:id>', views.refresh_state, name='slides_refresh'),
]

ailearn/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('native-admin/', admin.site.urls),
    path('', include('index.urls')),
    path('user/', include('user.urls')),
    path('problem/', include('problem.urls')),
    path('zone/', include('zone.urls')),
    path('chat/', include('chat.urls')),
    path('ai/', include('AI.urls')),
    path('tag/', include('tag.urls')),
    path('paper/', include('paper.urls')),
    path('admin/', include('adminc.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

paper/urls.py
from django.urls import path
from . import views

app_name = 'paper'

urlpatterns = [
    path('', views.index, name='index'),
    path('new/', views.new, name='new'),
    path('<int:id>/', views.view, name='view'),
    path('<int:id>/statistics/', views.statistics, name='statistics'),
    path('<int:id>/submission/', views.paper_submission, name='papersubmissions'),
    path('submission/', views.submissions, name='submissions'),
    path('submission/<int:id>/', views.submission, name='submission'),
    path('submission/<int:id>/judge/', views.judge, name='judge'),
]

paper/models.py
from django.db import models
from problem.models import  Problem
from django.utils.timezone import now
from user.models import *

class Paper(models.Model):
    facility = models.ForeignKey(Facility, on_delete = models.CASCADE, null = True)
    title = models.TextField(max_length=10)
    date = models.DateTimeField(default = now)

class PaperProblem(models.Model):
    paper = models.ForeignKey(Paper, on_delete=models.CASCADE)
    raw = models.ForeignKey(Problem, on_delete=models.CASCADE)
    score = models.IntegerField('problemScore', default=10)

class Submission(models.Model):
    student = models.ForeignKey(User, on_delete=models.CASCADE)
    paper = models.ForeignKey(Paper, on_delete=models.CASCADE)

class Answer(models.Model):
    submission = models.ForeignKey(Submission, on_delete=models.CASCADE, null=True)
    problem = models.ForeignKey(PaperProblem, on_delete=models.CASCADE)
    answer = models.CharField('answer', max_length=4096, default="未作答")
    score = models.IntegerField('markScore', default=0)
    date = models.DateTimeField(default = now)

paper/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.http.request import HttpRequest
from django.http import JsonResponse
from django.db.models import Q, Sum, Subquery, OuterRef
from rest_framework import status
from rest_framework.response import Response

from user.models import *
from tag.models import *
from functools import reduce
from problem.models import *
from paper.models import *
from problem.templatetags.markdown import unmarkup
from functional import seq
from collections import Counter
import json
import openai
from dotenv import load_dotenv
from django.http import HttpResponse
from django.http import *
from rest_framework.decorators import api_view, permission_classes
from rest_framework.permissions import IsAuthenticated
from rest_framework.exceptions import AuthenticationFailed
from user.views import get_user_from_token
from rest_framework.response import Response
load_dotenv()

OPENAI_API_KEY = os.getenv('OPENAI_KEY')
@permission_classes([IsAuthenticated])
def index(request: HttpRequest):
    token = request.headers.get('Authorization')
    user = get_user_from_token(token)
    if request.method == 'GET':
        papers = Paper.objects.filter(facility=user.facility)
        return Response(
            data={
                'data':{
                    'papers': papers
                },
                "message": "success"
        },status=status.HTTP_200_OK
        )
        # return render(request, 'paper/index.html', {
        #     'papers': papers,
        # })
@permission_classes([IsAuthenticated])
def view(request: HttpRequest, id: int):
    token = request.headers.get('Authorization')
    user = get_user_from_token(token)
    paper = Paper.objects.get(id=id)
    probblems = PaperProblem.objects.filter(paper=paper)

    if request.method == 'GET':
        # return render(request, 'paper/view.html', {
        #     'paper': paper,
        #     'problems': probblems,
        # })
        return Response(
            data= {
            'data': {
            'paper': paper,
            'problems': probblems
            },
            "message":"success"
        },status=status.HTTP_200_OK
        )
    if request.method == 'POST':

        sub = Submission.objects.create(student=user, paper=paper)

        for p in probblems:
            answer = Answer.objects.filter(
                submission=sub,
                problem=p,
            ).first()
            if answer is not None:
                answer.answer=request.POST[f'answer-{p.raw.id}']
                answer.save()
            else:
                Answer.objects.create(
                    problem=p,
                    submission=sub,
                    answer=request.POST[f'answer-{p.raw.id}']
                )
        # return redirect('paper:submission', sub.id)
        return Response(
            data={
            'data': {
            'submission': sub.id
            },
            "message":"success"
        },status=status.HTTP_200_OK
        )
@permission_classes([IsAuthenticated])
def new(request: HttpRequest):
    token = request.headers.get('Authorization')
    user = get_user_from_token(token)
    if request.method == 'GET':
        tags = Tag.objects.filter(problems__facility=user.facility).distinct()

        # return render(request, 'paper/new.html', {
        #     'tags': tags
        # })
        return Response(
            data={
            'data': {
            'tags': tags
            },
            "message":"success"
        },status=status.HTTP_200_OK
        )
    if request.method == 'POST':
        if request.POST['type'] == 'search':
            tags = json.loads(request.POST['tags'])
            result = reduce(lambda qs, tag: qs.filter(tag__id = tag), tags, Problem.objects.filter(facility=user.facility))
            
            return JsonResponse(
                data={
                'data': {
                'result': seq(result.values()).map(lambda x: {
                    **x,
                    'statement': unmarkup(x['statement'])
                }).to_list()
                }
            },status = status.HTTP_200_OK, safe=False)

        if request.POST['type'] == 'submit':
            problems = json.loads(request.POST['problems'])
            paper = Paper.objects.create(title=request.POST['title'], facility=user.facility)
            for id in problems:
                p = Problem.objects.get(pk = id)
                PaperProblem.objects.create(paper=paper, raw=p, score=request.POST[f'score{id}'])
           # return redirect('paper:view', paper.id)
        return Response(
            data={
            'data': {
            'paper': paper.id
            },
            "message":"success"
        },status=status.HTTP_200_OK
        )
@permission_classes([IsAuthenticated])
def submissions(request: HttpRequest):
    token = request.headers.get('Authorization')
    user = get_user_from_token(token)
    if request.method == 'GET':
        max_score = Paper.objects.filter(pk=OuterRef('paper_id')) \
            .annotate(max_score=Sum('paperproblem__score'))
        
        if user.role == 'student':
            sub = Submission.objects.filter(student=user) \
                .annotate(score=Sum('answer__score'),max_score=Subquery(max_score.values('max_score')))
            
        elif user.role == 'teacher':
            sub = Submission.objects.filter(student__facility=user.facility) \
                .annotate(score=Sum('answer__score'),max_score=Subquery(max_score.values('max_score')))
            
        # return render(request, 'paper/submissions.html', {
        #     'submissions': sub
        # })
        return Response(
            data={
            'data': {
            'submissions': sub
            },
            "message":"success"
        },status=status.HTTP_200_OK
        )
@permission_classes([IsAuthenticated])
def paper_submission(request: HttpRequest, id: int):
    token = request.headers.get('Authorization')
    user = get_user_from_token(token)
    if request.method == 'GET':
        if user.role == 'teacher':
            max_score = Paper.objects.filter(pk=OuterRef('paper_id')) \
                .annotate(max_score=Sum('paperproblem__score'))
            paper = Paper.objects.get(id=id)
            sub = Submission.objects.filter(paper=paper) \
                .annotate(score=Sum('answer__score'), total_score=Subquery(max_score.values('max_score')))
            # return render(request, 'paper/paper_submission.html', {
            #     'submissions': sub,
            #     'paper': paper,
            # })
            return Response(
                data={
                'data': {
                'submissions': sub,
                'paper': paper
                },
                "message":"success"
            },status=status.HTTP_200_OK
            )
        elif user.role == 'student':
            return Response(
                data={
                "message":"学生禁用此接口"
            },status=status.HTTP_403_FORBIDDEN
            )
@permission_classes([IsAuthenticated])
def submission(request: HttpRequest, id: int):
    token = request.headers.get('Authorization')
    user = get_user_from_token(token)
    s = Submission.objects.get(id=id)
    answer = Answer.objects.filter(submission=s)

    if request.method == 'POST':
        if s.student != user and user.role != 'teacher':
            return Response(
                data={
                "message":"无权限"
            },status=status.HTTP_403_FORBIDDEN
            )
        if request.POST.get('type') == 'analysis':
            openai.api_key = OPENAI_API_KEY
            openai.base_url = 'https://api.ai-yyds.com/v1/'

            cnt = 1
            qs = ''
            for ans in answer:
                pbl = ans.problem.raw
                q = f'第{cnt}道题：题目标题为：{ans.problem.raw.title}，题目内容为{ans.problem.raw.statement}，题目标准答案为：{ans.problem.raw.answer}，学生的答案为：{ans.answer}。'
                cnt += 1
                qs += q
                prompt = '''
                我会给你几道题的题目标题，题目内容，标准答案和我的答案，题目内容可能会包含markdown标记，你必须过滤这些标记，
                你的任务是根据题目，对照标准答案来分析我的答案，找出我的答案的问题，指出我知识的不足并给出学习建议，
                学习建议一定要根据题目和作答情况具体到某些知识点不能太笼统。
                每一道题都要给出分析和建议，在最后总结一下所有题目并总体评价一下学生的作答情况，给出合理的建议。
                你的输出包含分析、评价、建议之外的任何内容，
                不能包含任何不相关的前缀后缀类似"好的"，绝对不能出现与markdown相关的内容，绝对不能出现markdown标记符号，绝对不能出现markdown标记后隐藏的文字，不超过200字。
                '''
                messages = [
                    {
                        'role': 'user',
                        'content': prompt + qs
                    }
                ]
            response = openai.chat.completions.create(
                messages=messages,
                model='gpt-3.5-turbo'
            )
            return JsonResponse({
                'data': {
                'analysis': response.choices[0].message.content
                },
                'message': 'success'
            },status=status.HTTP_200_OK
            )
        else:
            return Response({
                "message":"无权限"
            },status=status.HTTP_403_FORBIDDEN
            )
    if request.method == 'GET':
        if s.student != user and user.role != 'teacher':
            return Response({
                "message":"无权限"
            },status=status.HTTP_403_FORBIDDEN
            )
        # return render(request, 'paper/submission.html', {
        #     'answer': answer,
        #     'submission': s,
        # })
        return Response({
            'data': {
            'answer': answer,
            'submission': s
            },
            "message":"success"
        },status=status.HTTP_200_OK
        )
@permission_classes([IsAuthenticated])
def judge(request: HttpRequest, id: int):
    token = request.headers.get('Authorization')
    user = get_user_from_token(token)
    if user.role != 'teacher':
        return Response({
            "message":"无权限"

paper/templates/paper/base.html
{% extends "base.html" %}

{% load static %}

{% block topmenu %}
<a class="item" href="{% url 'paper:index' %}" data-slave-app="paper">
    <i class="fa-solid fa-list"></i> 试题列表
</a>

<a class="item" href="{% url 'paper:submissions' %}" data-slave-app="paper">
    <i class="fa-solid fa-paper-plane"></i> 提交记录
</a>

{% if request.user.role == 'teacher' %}
<a class="item" href="{% url 'paper:new' %}" data-slave-app="paper">
    <i class="fa-solid fa-plus"></i> 新建试题
</a>
{% endif %}


{% endblock %}

paper/templates/paper/index.html
{% extends "paper/base.html" %}

{% load static %}

{% block content %}

<style>
    .ui.celled.padded.center.aligned.table {
        background-color: rgba(255, 255, 255, 0.662);
    }
</style>

<div class="ui center aligned text container" style="padding-top: 24px;">
    <h1>试卷列表</h1>
    <table class="ui center aligned celled table" style="background-color: #ffffffbe;">
        <thead>
            <tr>
                <th style="background-color: #ffffff00;">ID</th>
                <th style="background-color: #ffffff00;">标题</th>
                <th style="background-color: #ffffff00;">创建日期</th>
                {% if request.user.role == 'teacher' %}
                <th style="background-color: #ffffff00;">导航</th>
                {% endif %}
            </tr>
        </thead>
        <tbody>
            {% for paper in papers %}
            <tr>
                <td>{{ paper.id }}</td>
                <td><a href="{% url 'paper:view' paper.id %}">{{ paper.title }}</a></td>
                <td>{{ paper.date | date:"Y/m/d" }}</td>
                {% if request.user.role == 'teacher' %}
                <td>
                    <a href="{%  url 'paper:papersubmissions' paper.id %}">
                        提交记录
                    </a>
                    <a href="{%  url 'paper:statistics' paper.id %}">
                        统计
                    </a>
                </td>
                {% endif %}
            </tr>
            {% endfor %}
        </tbody>
    </table>
    <ul id="paper-list">
    </ul>
</div>

{% endblock %}

paper/templates/paper/judge.html
{% extends "paper/base.html" %}

{% load static %}
{% load markdown %}

{% block content %}
<div class="ui padded text container segment" style="padding-top: 24px; background-color: #ffffffac;">
    <h1 class="ui center aligned header" style="margin-top: 24px;text-align: center;">批改试卷 | {{ submission.paper.title }}</h1>

    <form method="post">
        {% csrf_token %}

        {% for answer in answers %}
        <div class="ui left aligned container">
            <h2>
                {{ forloop.counter }}. {{ answer.problem.raw.title }} ({{ answer.problem.score }} 分)
            </h2>
            <div>
                {{ answer.problem.raw.statement | markdown | safe }}
            </div>

            <h4 style="margin-top: 24px;text-align: center;">
                {{ submission.student.username }}的答案：{{ answer.answer }}
            </h4>
        </div>
        <div class="ui fluid input">
            <input type="number" min="0" placeholder="给这道题评分..." max="{{ answer.problem.score }}" name="score-{{ answer.id }}">
        </div>
        {% endfor %}
        <div class="ui center aligned grid" style="margin-top: 24px;">
            <button class="ui green button" type="submit">
                <i class="fa-solid fa-check"></i> 提交
            </button>
        </div>
    </form>
</div>

{% endblock %}

paper/templates/paper/new.html
{% extends "paper/base.html" %}

{% load static %}

{% block head %}
<style>
    .search-box {
        margin-bottom: 20px;
    }

    .question {
        margin-bottom: 10px;
    }

</style>
{% endblock %}

{% block content %}
<input type="hidden" id="ajax-url" value='{% url "paper:new" %}'>
<input type="hidden" id="index-url" value='{% url "paper:index" %}'>
<input type="hidden" id="csrf-token" value='{{csrf_token}}'>
<div class="ui center aligned relaxed grid" style="padding-top: 24px;">
    <div class="row">
        <div class="six wide computer six wide tablet sixteen wide mobile column ui segment" style="background-color: #ffffffa8;">
            <h1 class="ui row">
                新建试卷
            </h1>

            <form method="post">

                {% csrf_token %}
                <input type="hidden" name="type" value="submit">
                <input type="hidden" name="problems">
                <div class="ui right labeled fluid input">
                    <input type="text" placeholder="试卷标题" name="title">
                    <button class="ui label button" type="submit">
                        提交
                    </button>
                </div>


                <h2>已选择的题目</h2>
                <table class="ui center aligned celled table">
                    <thead>
                        <tr>
                            <th id="list">ID</th>
                            <th id="list">标题</th>
                            <th id="list">分值</th>
                            <th id="list">操作</th>
                        </tr>
                    </thead>
                    <tbody id="selected-problems">

                    </tbody>
                    <tfoot>

                    </tfoot>
                </table>
            </form>
        </div>
        <div class="four wide computer four wide tablet sixteen wide mobile column ui segment" style="background-color: #ffffffa8;">
            <h2>搜索题目</h2>
            <div class="ui form">
                <div class="ui inverted dimmer">
                    <div class="ui text loader">正在加载</div>
                </div>
                <div class="field">
                    <div class="ui multiple search selection dropdown">
                        <input type="hidden" name="tags">
                        <i class="dropdown icon"></i>
                        <div class="default text">选择标签...</div>
                        <div class="menu">
                            {% for tag in tags %}
                            <div class="item" data-value="{{ tag.id }}">{{ tag.text }}</div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
                <div class="ui left aligned middle aligned container">
                    <div class="ui relaxed list" id="search-results">
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script src="{% static 'js/paper/new.js' %}"></script>

{% endblock %}

paper/templates/paper/paper_submission.html
{% extends "paper/base.html" %}

{% block content %}

<style>
    .ui.center.aligned.celled.table {
        background-color: rgba(255, 255, 255, 0.8);
    }
</style>

<div class="ui center aligned grid" style="padding-top: 24px">
    <div class="ten wide computer ten wide tablet sixteen wide mobile column">
        <h1>{{paper.title}} 的所有提交</h1>

        <table class="ui center aligned celled table">
            <thead>
                <tr>
                    <th style="background-color: #ffffff00;">ID</th>
                    <th style="background-color: #ffffff00;">提交者</th>
                    <th style="background-color: #ffffff00;">分数</th>
                    <th style="background-color: #ffffff00;">操作</th>
                </tr>
            </thead>

            <tbody>
                {% for sub in submissions %}
                <tr>
                    <td>{{ sub.id }}</td>
                    <td>{{ sub.student.username }}</td>
                    <td>{{ sub.score }} / {{ sub.total_score }}</td>
                    <td>
                        <a href="{% url 'paper:submission' sub.id %}">
                            查看
                        </a>
                        {% if request.user.role == 'teacher' %}
                        <a href="{% url 'paper:judge' sub.id %}">
                            批改
                        </a>
                        {% endif %}
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>

{% endblock %}

paper/templates/paper/statistics.html
{% extends "paper/base.html" %}

{% load markdown %}

{% block content %}

<div class="ui center aligned grid" style="padding-top: 24px">
    <div class="ui eight wide column segment" style="background-color: #ffffffc1;">
        <h1 class="ui header">
            {{ paper.title }} 的成绩分布图
        </h1>
        <canvas id="statistics" />
    </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>

<script>
    const maxScore = Number('{{ paper.sum_score }}');
    const scores = JSON.parse('{{ count | safe }}');
    const grain = 5;

    const data = [];
    const labels = [];

    for (let i = 0; i < maxScore; i += grain) {
        let val = 0;
        for (let j = i; j < i + grain; ++j) {
            val += scores[j] ?? 0;
        }
        data.push(val);
        labels.push(`${i} ~ ${i + grain - 1}`);
    }

    new Chart(document.getElementById('statistics'), {
        type: 'bar',
        data: {
            labels: labels,
            datasets: [{
                label: '学生人数',
                data: data
            }]
        }
    });
</script>

{% endblock %}

paper/templates/paper/submission.html
{% extends "paper/base.html" %}
{% load static %}

{% load markdown %}

{% block content %}
<input type="hidden" id="ajax-url" value='{% url "paper:submission" submission.id %}'>
<input type="hidden" id="csrf-token" value='{{csrf_token}}'>
<div class="ui center aligned grid">
    <div class="ui eleven wide column segment" style="background-color: #ffffffc1;">
        <div class="padded text container">
            <h1 class="ui header">{{ submission.paper.title }}</h1>
            <p>{{ submission.student.username }} 的提交</p>
            <div class="ui divider"></div>
            <div>
                {% for ans in answer %}
                <div>
                    <h3 style="text-align: left;">
                        {{ forloop.counter }}. {{ ans.problem.raw.title }}
                    </h3>

                    <div style="text-align: left;">
                        {{ ans.problem.raw.statement | markdown | safe }}
                    </div>

                    <h3>

                    </h3>
                    <h4 class="ui horizontal divider">
                        学生答案
                    </h4>
                    <div class="ui form">
                        <div class="field">
                            <textarea style="background-color: #ffffffc1;" readonly>{{ ans.answer }}</textarea>
                        </div>
                    </div>
                    得分：{{ ans.score }} / {{ ans.problem.score }}
                </div>
                <div class="ui divider"></div>
                {% endfor %}
            </div>
        </div>
    </div>
    <div class="row">
        <div class="ui eleven wide column segment">
            <div class="ui top attached label">AI分析</div>
            <div class="padded text container">
                <div id="skeleton" style="display: '';">
                    <div class="ui placeholder">
                        <div class="long line"></div>
                        <div class="short line"></div>
                        <div class="long line"></div>
                        <div class="short line"></div>
                        <div class="short line"></div>
                        <div class="long line"></div>
                        <div class="short line"></div>
                    </div>
                </div>
                <div class="ui form" id="analysis-ui" style="display: none;">
                    <div class="field">
                        <textarea id="analysis" readonly></textarea>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script src="{% static 'js/paper/submission.js' %}"></script>
{% endblock %}

paper/templates/paper/submissions.html
{% extends "paper/base.html" %}

{% block content %}

<div class="ui center aligned grid" style="padding-top: 24px">
    <div class="ten wide computer ten wide tablet sixteen wide mobile column">
        <h1>试卷提交记录</h1>

        <table class="ui center aligned celled table" style="background-color: rgba(255, 255, 255, 0.8);">
            <thead>
                <tr>
                    <th style="background-color: #ffffff00;">ID</th>
                    <th style="background-color: #ffffff00;">试卷标题</th>
                    <th style="background-color: #ffffff00;">总分</th>
                    <th style="background-color: #ffffff00;">操作</th>
                </tr>
            </thead>

            <tbody>
                {% for sub in submissions %}
                <tr>
                    <td>{{ sub.id }}</td>
                    <td>{{ sub.paper.title }}</td>
                    <td>{{ sub.score }} / {{ sub.max_score }}</td>
                    <td>
                        <a href="{% url 'paper:submission' sub.id %}">
                            查看
                        </a>
                        {% if request.user.role == 'teacher' %}
                        <a href="{% url 'paper:judge' sub.id %}">
                            批改
                        </a>
                        {% endif %}
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>

{% endblock %}

paper/templates/paper/view.html
{% extends "paper/base.html" %}

{% load static %}
{% load markdown %}

{% block content %}
<div class="ui padded text container segment" style="padding-top: 24px;background-color: #ffffffc1;">
    <h1 class="ui header">{{ paper.title }}</h1>
    <form method="post">
        {% csrf_token %}
        {% for problem in problems %}
        <div class="problem" data-pid="{{ problem.id }}">
            <h2>
                {{ forloop.counter }}. {{ problem.raw.title }} ({{ problem.score }} 分)
            </h2>
            <div>
                {{ problem.raw.statement | markdown | safe }}
            </div>
            <div class="ui form">
                <div class="field">
                    <textarea style="background-color: #ffffffc1;" name="answer-{{ problem.raw.id }}" placeholder="填写答案..."></textarea>
                </div>
            </div>
        </div>
        {% endfor %}
        <div class="ui center aligned grid" style="margin-top: 24px;">
            <button class="ui green button" type="submit">
                <i class="fa-solid fa-check"></i> 提交
            </button>
        </div>
    </form>
</div>

{% endblock %}