AI/urls.py
from django.urls import path
from . import views

app_name = 'AI'

urlpatterns = [
    path('gpt', views.gpt, name='gpt'),
    path('slides', views.genppt, name='slides'),
    path('slides/refresh/<int:id>', views.refresh_state, name='slides_refresh'),
]

adminc/urls.py
from django.urls import path
from . import views

app_name = 'adminc'

urlpatterns = [
    path('user/', views.user, name='user'),
    path('student/', views.student, name='student'),
    path('facility/', views.facility, name='facility')
]

ailearn/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('native-admin/', admin.site.urls),
    path('', include('index.urls')),
    path('user/', include('user.urls')),
    path('problem/', include('problem.urls')),
    path('zone/', include('zone.urls')),
    path('chat/', include('chat.urls')),
    path('ai/', include('AI.urls')),
    path('tag/', include('tag.urls')),
    path('paper/', include('paper.urls')),
    path('admin/', include('adminc.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

index/urls.py
from django.urls import path
from . import views

app_name = 'index'

urlpatterns = [
    path('', views.index, name='index')
]

paper/urls.py
from django.urls import path
from . import views

app_name = 'paper'

urlpatterns = [
    path('', views.index, name='index'),
    path('new/', views.new, name='new'),
    path('<int:id>/', views.view, name='view'),
    path('<int:id>/statistics/', views.statistics, name='statistics'),
    path('<int:id>/submission/', views.paper_submission, name='papersubmissions'),
    path('submission/', views.submissions, name='submissions'),
    path('submission/<int:id>/', views.submission, name='submission'),
    path('submission/<int:id>/judge/', views.judge, name='judge'),
]

zone/urls.py
from django.urls import path
from . import views

app_name = 'zone'

urlpatterns = [
    path('', views.index, name='index'),
    path('new/', views.new, name='new'),
    path('<int:id>/', views.view, name='view'),
]

templates/component/sidebar.html
{% load static %}

<div class="item">
    <a class="ui logo icon image" href="{% url 'index:index' %}">
        <img src="{% static 'img/logo.png' %}" style="height:50px;">
    </a>
</div>
<a class="item" href="{% url 'index:index' %}" data-app="index" style="padding: 2rem; display: flex; align-items: center;">
    <i class="fa-solid fa-house" style="margin-right: 8px;"></i> 
    <span style="margin-left: 10px;">首页</span>
</a>
<a class="item" href="{% url 'problem:index' %}" data-app="problem" style="padding: 2rem; display: flex; align-items: center;">
    <i class="fa-solid fa-pen" style="margin-right: 8px;"></i>
    <span style="margin-left: 10px;">智慧题集</span>
</a>
<a class="item" href="{% url 'paper:index' %}" data-app="paper" style="padding: 2rem; display: flex; align-items: center;">
    <i class="fa-solid fa-paperclip" style="margin-right: 8px;"></i>
    <span style="margin-left: 10px;">云测考场</span>
</a>
<a class="item" href="{% url 'zone:index' %}" data-app="discussion" style="padding: 2rem; display: flex; align-items: center;">
    <i class="fa-solid fa-newspaper" style="margin-right: 8px;"></i>
    <span style="margin-left: 10px;">文思论坛</span>
</a>
<a class="item" href="{% url 'AI:gpt' %}" data-app="ai" style="padding: 2rem; display: flex; align-items: center;">
    <i class="fa-solid fa-robot" style="margin-right: 8px;"></i>
    <span style="margin-left: 10px;">AI助学</span>
</a>
{% if request.user.role == 'teacher' and  not request.user.is_staff%}
<a class="item" href="{% url 'adminc:student' %}" data-app="teacher" style="padding: 2rem; display: flex; align-items: center;">
    <i class="fa-solid fa-user" style="margin-right: 8px;"></i>
    <span style="margin-left: 10px;">后台管理</span>
</a>
{% endif %}
{% if request.user.is_staff %}
<a class="item" href="{% url 'adminc:user' %}" data-app="admin" style="padding: 2rem; display: flex; align-items: center;">
    <i class="fa-solid fa-user-tie" style="margin-right: 8px;"></i>
    <span style="margin-left: 10px;">后台管理</span>
</a>
{% endif %}