AI/urls.py
from django.urls import path
from . import views

app_name = 'AI'

urlpatterns = [
    path('gpt', views.gpt, name='gpt'),
    path('slides', views.genppt, name='slides'),
    path('slides/refresh/<int:id>', views.refresh_state, name='slides_refresh'),
]

ailearn/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('native-admin/', admin.site.urls),
    path('', include('index.urls')),
    path('user/', include('user.urls')),
    path('problem/', include('problem.urls')),
    path('zone/', include('zone.urls')),
    path('chat/', include('chat.urls')),
    path('ai/', include('AI.urls')),
    path('tag/', include('tag.urls')),
    path('paper/', include('paper.urls')),
    path('admin/', include('adminc.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

chat/urls.py
from django.urls import path
from . import views
app_name = 'chat'
urlpatterns = [
    path('', views.chat, name='chat'),
]

zone/urls.py
from django.urls import path
from . import views

app_name = 'zone'

urlpatterns = [
    path('', views.index, name='index'),
    path('new/', views.new, name='new'),
    path('<int:id>/', views.view, name='view'),
]

tag/models.py
from django.db import models
from problem.models import  Problem
from zone.models import Post
from user.models import User

class Tag(models.Model):
    text = models.TextField(max_length=10)
    problems = models.ManyToManyField(Problem)
    post = models.ManyToManyField(Post)
    user = models.ManyToManyField(User)

class UserTagWeight(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    tag = models.ForeignKey(Tag, on_delete=models.CASCADE)
    weight = models.IntegerField('weight', default=0)

zone/models.py
from django.db import models
import datetime
from django.utils import timezone

from user.models import *
from django.conf import settings

def now():
    return timezone.now()

class Post(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length = 255, default = '')
    content = models.TextField()
    facility = models.ForeignKey(Facility, on_delete = models.CASCADE, null = True)
    date = models.DateTimeField(default = now)

class Comment(models.Model):
    post = models.ForeignKey(Post, null = True, on_delete = models.CASCADE)
    author = models.ForeignKey(User, on_delete = models.CASCADE)
    content = models.TextField()
    reply = models.ForeignKey('self', null = True, on_delete = models.CASCADE)
    date = models.DateTimeField(default = now)

zone/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.http import HttpRequest
from .models import *
from tag.models import *
from user.models import *
from django.http import HttpResponse
from rest_framework import status
from rest_framework.response import Response
from rest_framework.decorators import api_view, permission_classes
from rest_framework.permissions import IsAuthenticated
from rest_framework.exceptions import AuthenticationFailed
from user.views import get_user_from_token
@permission_classes([IsAuthenticated])
def index(request):
    token = request.headers.get('Authorization')
    user = get_user_from_token(token)
    posts = Post.objects.filter(facility = user.facility).order_by('date')
    return Response(
        data = {
            "posts": posts,
        },
        status = 200
    )
@permission_classes([IsAuthenticated])
@api_view(['POST'])
def new(request: HttpRequest):
    token = request.headers.get('Authorization')
    user = get_user_from_token(token)
    post = Post.objects.create(
            author = user,
            title = request.POST['title'],
            content = request.POST['content'],
            facility = user.facility,
        )
    tags = request.POST['tag']
    tag_ls = tags.split(';')
    for t in tag_ls:
        ta = t.strip()
        if ta:
            tag = Tag.objects.filter(text=ta).first()
            if tag is not None:
                tag.post.add(post)
            else:
                tmpT = Tag.objects.create(text = ta)
                tmpT.post.add(post)
    post.save()
    return Response(
        status = 200
        ,data = {
            'data': {
            "post": post.id
            }
        }
        )
@permission_classes([IsAuthenticated])
def view(request: HttpRequest, id: int):
    token = request.headers.get('Authorization')
    user = get_user_from_token(token)
    post = Post.objects.get(id = id)

    if request.method == 'GET':
        comments = Comment.objects.filter(post = post)

        if post is None:
            return Response(
                status = 404
            )
        return Response(
            status = 200
            ,data = {
                'data': {
                "post": post,
                "comments": comments
                },
                'message':"success"
            }
        )
    elif request.method == 'POST':
        comment = Comment.objects.create(
            author = user,
            post = post,
            reply = Comment.objects.get(id = int(request.POST['reply'])) if request.POST['reply'] else None,
            content = request.POST['comment']
        )
        comment.save()
        return Response(
            status = 200
            ,data = {
                'data': {
                "id": id
                }
                ,'message':"success"
            }
        )

zone/templates/zone/base.html
{% extends "base.html" %}

{% load static %}

{% block topmenu %}
<a class="item" href="{% url 'zone:index' %}" data-slave-app="discussion">
    <i class="fa-solid fa-list"></i> 文章列表
</a>

<a class="item" href="{% url 'chat:chat' %}" data-slave-app="discussion">
    <i class="fa-solid fa-comments"></i> 聊天室
</a>

<a class="item" href="{% url 'zone:new' %}" data-slave-app="discussion">
    <i class="fa-solid fa-pen-to-square"></i> 新文章
</a>

{% endblock %}

zone/templates/zone/index.html
{% extends "zone/base.html" %}
{% load static %}
{% load markdown %}

{% block content %}
<div class="ui center aligned middle aligned grid" style="min-height: 100%;">
    <div class="ten wide computer ten wide tablet sixteen wide mobile column">
        {% for post in posts %}
        <div class="ui segment" style="background-color: rgba(255, 255, 255, 0.607);">
            <h1>
                <a href="{% url 'zone:view' post.id %}" style="color:inherit">
                    {% if post.title %}
                    {{ post.title }}
                    {% else %}
                    <i>无标题</i>
                    {% endif %}
                </a>
            </h1>

            <p>
                {{ post.date|date:"Y/m/d"}} | 由 {{ post.author.username }} 撰写
            </p>

            <div>
                {{ post.content|truncatechars:32|unmarkdown }}
            </div>

            <div style="font-weight: bold;color: rgb(232, 96, 23);">
                {% for tag in post.tag_set.all %}
                {{ tag.text }}
                {% endfor %}
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

zone/templates/zone/new.html
{% extends "zone/base.html" %}

{% load static %}

{% block content %}
<style>
    .editor-container {
        text-align: left !important;
    }

</style>


<div class="ui center aligned middle aligned grid" style="min-height: 100%">
    <div class="ten wide computer ten wide tablet sixteen wide mobile column ui segment">
        <h1>
            新文章
        </h1>
        <form method="POST">
            {% csrf_token %}
            <div class="ui form">
                <div class="field">
                    <input type="text" name="title" placeholder="标题" id="input-title" required>
                </div>

                <div class="field editor-container" >
                    <textarea id="editor" ></textarea>
                </div>
                
                <input type="hidden" name="content" id="input-content">

                <div class="field">
                    <input name="tag" placeholder="文章标签 用 ; 分割" id="input-tag">
                </div>

                <button class="ui primary button" type="submit">
                    <i class="fa-solid fa-paper-plane"></i> GO
                </button>
            </div>
        </form>
    </div>
</div>

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/easymde/dist/easymde.min.css">
<script src="https://cdn.jsdelivr.net/npm/easymde/dist/easymde.min.js"></script>

<script>
    const mde = new EasyMDE({
        element: document.getElementById('editor'),
        minHeight: '500px',
        maxHeight: '500px',
        spellChecker: false,
        placeholder: '文章内容'
    });

    $('form').submit(function () {
        $(this).find('input[name="content"]').val(mde.value());
        return true;
    });
</script>


{% endblock %}

zone/templates/zone/view.html
{% extends "zone/base.html" %}
{% load static %}
{% load markdown %}

{% block content %}
<div class="ui container segment">
    <div class="ui text container">
        <h1 style="text-align: center;">
            {{ post.title | default:"<i>无标题</i>" }}
        </h1>
        
        <p style="text-align: center;color: #000;">
            {{ post.date|date:"Y/m/d"}} | 由 {{ post.author.username }} 撰写
        </p>
        <div class="ui segment" id="post-back">
        <div>
            {{ post.content | markdown | safe }}
        </div>
        </div>
    </div>

    <div class="ui horizontal divider">
        评论
    </div>

    <div class="ten wide computer ten wide tablet sixteen wide mobile column">

        <div class="ui text container" >
            <form method="POST">
                {% csrf_token %}
                <div class="ui form">
                    <input type="hidden" name="reply" id="input-reply-id">
                    <p id="text-reply"></p>
                    <div class="field" style="display: flex;">
                        <input name="comment" placeholder="输入评论..." required>
                        <button class="ui button" type="submit" style="font-weight: bold;">GO</button>
                    </div>

                </div>
            </form>
        </div>

        <div class="ui text container comment-container">
            <div class="ui segment" id="post-back">
            {% for comment in comments %}
            <div class="ui left aligned container comment" style="margin: 12px;"
                data-reply="{{ comment.reply.id | default:'' }}" data-id="{{ comment.id }}">
                
                <span>
                    <b>
                        {{ comment.author.username }}
                    </b>
                    <span class="comment-date"> #{{ comment.id }} {{ comment.date|date:"Y/m/d H:i:s" }}</span>
                    <a onClick="setReply(Number('{{ comment.id }}'))" class="comment-reply-button">回复</a>
                </span>
                <p>
                    {{ comment.content }}
                </p>

                <div class="reply-container">
                </div>
            </div>
            {% empty %}
            <i>
                暂无评论
            </i>
        </div>
            {% endfor %}
        </div>
    </div>
</div>

<script>
    function setReply(id) {
        $('#input-reply-id').val(id);
        $('#text-reply').text('回复 #' + id.toString());
    }

    $('.comment').filter((i, e) => $(e).data('reply') != '')
        .each((i, e) => {
            const target = $('.comment').filter((j, f) => $(e).data('reply') == $(f).data('id'));
            $(e).appendTo(target.first().children('.reply-container'))
        })
</script>
{% endblock %}